In [3]:
import geopandas as gpd

path = r"D:\PredictRoute\new_delhi_traffic_dataset\probe_counts\geojson\new_delhi__2024-08-11_to_2024-08-11_.geojson"

df = gpd.read_file(path)

df.head()

,jobName,creationTime,segmentId,newSegmentId,speedLimit,frc,streetName,distance,segmentProbeCounts,userPreference,dateRanges,timeSets,networkName,zoneId,probeSource,mapsVersions,geometry
0,new_delhi (2024-08-11 to 2024-08-11),2025-02-10 20:01:36.993000+00:00,NaN,None,NaN,NaN,None,NaN,None,"{'distanceUnit': 'KILOMETERS', 'includedSpeedL...","[{'@id': 1, 'name': '2024-08-11 to 2024-08-11'...","[{'@id': 2, 'name': '0:00-1:00', 'dayToTimeRan...",new_delhi,Asia/Kolkata,ALL,[India_ind2024.12.000-22.343-0 DSEG_NOSPLIT],None
1,None,NaT,-1.356011e+13,-00004e30-3400-0400-0000-0000008bad86,45.0,6.0,Ghata Masjid Road,20.87,"[{'timeSet': 2, 'dateRange': 1, 'probeCount': ...",None,None,None,None,None,None,None,"LINESTRING (77.24376 28.64596, 77.2437 28.6460..."
2,None,NaT,-1.356012e+13,-00004e30-3400-0400-0000-0000008badbe,45.0,6.0,Vishnu Mandir Marg,37.46,"[{'timeSet': 2, 'dateRange': 1, 'probeCount': ...",None,None,None,None,None,None,None,"LINESTRING (77.18502 28.64689, 77.18523 28.64717)"
3,None,NaT,-1.356014e+13,-00004e30-3400-0400-0000-0000008bae1c,45.0,3.0,Ram Nagar Gali Number 2,5.92,"[{'timeSet': 2, 'dateRange': 1, 'probeCount': ...",None,None,None,None,None,None,None,"LINESTRING (77.21794 28.64632, 77.21788 28.64631)"
4,None,NaT,-1.356011e+13,-00004e30-3400-0400-0000-0000008bae40,45.0,6.0,Sat Bhirawan Road,61.53,"[{'timeSet': 2, 'dateRange': 1, 'probeCount': ...",None,None,None,None,None,None,None,"LINESTRING (77.19444 28.64713, 77.19441 28.647..."

In [4]:
df.shape

(24939, 17)

In [5]:
df.isnull().sum()

jobName               24938
creationTime          24938
segmentId                 1
newSegmentId              1
speedLimit                1
frc                       1
streetName             2230
distance                  1
segmentProbeCounts        1
userPreference        24938
dateRanges            24938
timeSets              24938
networkName           24938
zoneId                24938
probeSource           24938
mapsVersions          24938
geometry                  1
dtype: int64

In [6]:
df.columns

Index(['jobName', 'creationTime', 'segmentId', 'newSegmentId', 'speedLimit',
       'frc', 'streetName', 'distance', 'segmentProbeCounts', 'userPreference',
       'dateRanges', 'timeSets', 'networkName', 'zoneId', 'probeSource',
       'mapsVersions', 'geometry'],
      dtype='object')

In [7]:
col = ['jobName', 'creationTime', 'userPreference',
       'dateRanges', 'timeSets', 'networkName', 'zoneId', 'probeSource',
       'mapsVersions']

df = df.drop(columns=col, index=[1])

In [8]:
df = df.drop(index=[0])
df

,segmentId,newSegmentId,speedLimit,frc,streetName,distance,segmentProbeCounts,geometry
2,-1.356012e+13,-00004e30-3400-0400-0000-0000008badbe,45.0,6.0,Vishnu Mandir Marg,37.46,"[{'timeSet': 2, 'dateRange': 1, 'probeCount': ...","LINESTRING (77.18502 28.64689, 77.18523 28.64717)"
3,-1.356014e+13,-00004e30-3400-0400-0000-0000008bae1c,45.0,3.0,Ram Nagar Gali Number 2,5.92,"[{'timeSet': 2, 'dateRange': 1, 'probeCount': ...","LINESTRING (77.21794 28.64632, 77.21788 28.64631)"
4,-1.356011e+13,-00004e30-3400-0400-0000-0000008bae40,45.0,6.0,Sat Bhirawan Road,61.53,"[{'timeSet': 2, 'dateRange': 1, 'probeCount': ...","LINESTRING (77.19444 28.64713, 77.19441 28.647..."
5,-1.356013e+13,-00004e30-3400-0400-0000-0000008baf73,45.0,6.0,Vishnu Mandir Marg,31.10,"[{'timeSet': 2, 'dateRange': 1, 'probeCount': ...","LINESTRING (77.18486 28.64665, 77.18502 28.64689)"
6,-1.356011e+13,-00004e30-3400-0400-0000-0000008bb01f,45.0,6.0,Prakash Chand Jain Marg,41.99,"[{'timeSet': 2, 'dateRange': 1, 'probeCount': ...","LINESTRING (77.24383 28.64559, 77.24376 28.64596)"
...,...,...,...,...,...,...,...,...
24934,1.356034e+13,ffe6e0d4-8c49-46ff-bc4c-d133ef8dcea3,50.0,6.0,Chandragupta Marg,86.78,"[{'timeSet': 2, 'dateRange': 1, 'probeCount': ...","LINESTRING (77.18246 28.59395, 77.18237 28.593..."
24935,1.356034e+13,fff045f4-92e4-4ea4-815c-8245c70bb6db,50.0,4.0,Kaifi Azami Marg,35.30,"[{'timeSet': 2, 'dateRange': 1, 'probeCount': ...","LINESTRING (77.17826 28.57042, 77.17834 28.570..."
24936,1.356033e+13,fff048d9-fa80-4292-989f-eebd48ebfd2b,55.0,6.0,Eastern Avenue,87.96,"[{'timeSet': 2, 'dateRange': 1, 'probeCount': ...","LINESTRING (77.26701 28.57039, 77.26696 28.570..."
24937,1.356032e+13,fff5558c-87dc-4df5-bc43-e4c71869d2a6,50.0,2.0,Aurobindo Marg,134.90,"[{'timeSet': 2, 'dateRange': 1, 'probeCount': ...","LINESTRING (77.20609 28.55549, 77.20613 28.555..."
24938,1.356034e+13,fffbe947-5a15-42df-b2c8-6e242db662d4,45.0,6.0,None,35.10,"[{'timeSet': 2, 'dateRange': 1, 'probeCount': ...","LINESTRING (77.30213 28.63136, 77.30179 28.63125)"

In [14]:
df

,segmentId,newSegmentId,speedLimit,frc,streetName,distance,segmentProbeCounts,geometry
2,-1.356012e+13,-00004e30-3400-0400-0000-0000008badbe,45.0,6.0,Vishnu Mandir Marg,37.46,"[{'timeSet': 2, 'dateRange': 1, 'probeCount': ...","LINESTRING (77.18502 28.64689, 77.18523 28.64717)"
3,-1.356014e+13,-00004e30-3400-0400-0000-0000008bae1c,45.0,3.0,Ram Nagar Gali Number 2,5.92,"[{'timeSet': 2, 'dateRange': 1, 'probeCount': ...","LINESTRING (77.21794 28.64632, 77.21788 28.64631)"
4,-1.356011e+13,-00004e30-3400-0400-0000-0000008bae40,45.0,6.0,Sat Bhirawan Road,61.53,"[{'timeSet': 2, 'dateRange': 1, 'probeCount': ...","LINESTRING (77.19444 28.64713, 77.19441 28.647..."
5,-1.356013e+13,-00004e30-3400-0400-0000-0000008baf73,45.0,6.0,Vishnu Mandir Marg,31.10,"[{'timeSet': 2, 'dateRange': 1, 'probeCount': ...","LINESTRING (77.18486 28.64665, 77.18502 28.64689)"
6,-1.356011e+13,-00004e30-3400-0400-0000-0000008bb01f,45.0,6.0,Prakash Chand Jain Marg,41.99,"[{'timeSet': 2, 'dateRange': 1, 'probeCount': ...","LINESTRING (77.24383 28.64559, 77.24376 28.64596)"
...,...,...,...,...,...,...,...,...
24934,1.356034e+13,ffe6e0d4-8c49-46ff-bc4c-d133ef8dcea3,50.0,6.0,Chandragupta Marg,86.78,"[{'timeSet': 2, 'dateRange': 1, 'probeCount': ...","LINESTRING (77.18246 28.59395, 77.18237 28.593..."
24935,1.356034e+13,fff045f4-92e4-4ea4-815c-8245c70bb6db,50.0,4.0,Kaifi Azami Marg,35.30,"[{'timeSet': 2, 'dateRange': 1, 'probeCount': ...","LINESTRING (77.17826 28.57042, 77.17834 28.570..."
24936,1.356033e+13,fff048d9-fa80-4292-989f-eebd48ebfd2b,55.0,6.0,Eastern Avenue,87.96,"[{'timeSet': 2, 'dateRange': 1, 'probeCount': ...","LINESTRING (77.26701 28.57039, 77.26696 28.570..."
24937,1.356032e+13,fff5558c-87dc-4df5-bc43-e4c71869d2a6,50.0,2.0,Aurobindo Marg,134.90,"[{'timeSet': 2, 'dateRange': 1, 'probeCount': ...","LINESTRING (77.20609 28.55549, 77.20613 28.555..."
24938,1.356034e+13,fffbe947-5a15-42df-b2c8-6e242db662d4,45.0,6.0,None,35.10,"[{'timeSet': 2, 'dateRange': 1, 'probeCount': ...","LINESTRING (77.30213 28.63136, 77.30179 28.63125)"

In [13]:
df["newSegmentId"].loc[2]

'-00004e30-3400-0400-0000-0000008badbe'

In [20]:
df.loc[5, 'segmentProbeCounts']

[{'timeSet': 2, 'dateRange': 1, 'probeCount': 1},
 {'timeSet': 3, 'dateRange': 1, 'probeCount': 1},
 {'timeSet': 4, 'dateRange': 1, 'probeCount': 0},
 {'timeSet': 5, 'dateRange': 1, 'probeCount': 1},
 {'timeSet': 6, 'dateRange': 1, 'probeCount': 0},
 {'timeSet': 7, 'dateRange': 1, 'probeCount': 0},
 {'timeSet': 8, 'dateRange': 1, 'probeCount': 0},
 {'timeSet': 9, 'dateRange': 1, 'probeCount': 1},
 {'timeSet': 10, 'dateRange': 1, 'probeCount': 0},
 {'timeSet': 11, 'dateRange': 1, 'probeCount': 1},
 {'timeSet': 12, 'dateRange': 1, 'probeCount': 0},
 {'timeSet': 13, 'dateRange': 1, 'probeCount': 3},
 {'timeSet': 14, 'dateRange': 1, 'probeCount': 2},
 {'timeSet': 15, 'dateRange': 1, 'probeCount': 7},
 {'timeSet': 16, 'dateRange': 1, 'probeCount': 5},
 {'timeSet': 17, 'dateRange': 1, 'probeCount': 2},
 {'timeSet': 18, 'dateRange': 1, 'probeCount': 1},
 {'timeSet': 19, 'dateRange': 1, 'probeCount': 2},
 {'timeSet': 20, 'dateRange': 1, 'probeCount': 0},
 {'timeSet': 21, 'dateRange': 1, 'probeCount': 4},
 {'timeSet': 22, 'dateRange': 1, 'probeCount': 4},
 {'timeSet': 23, 'dateRange': 1, 'probeCount': 2},
 {'timeSet': 24, 'dateRange': 1, 'probeCount': 0},
 {'timeSet': 25, 'dateRange': 1, 'probeCount': 2}]